version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
     - gauravkhrnr

  configserver:
    image: gauravkhrnr/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - gauravkhrnr
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      
  eurekaserver:
    image: gauravkhrnr/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - gauravkhrnr
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  transit:
    image: gauravkhrnr/transit:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - gauravkhrnr
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  
  gatewayserver:
    image: gauravkhrnr/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - gauravkhrnr
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  gauravkhrnr: